max-blocks-to-send: 200 # The maximum number of blocks to send from each shard node to the oram node during evictions
eviction-rate: 2 # How many ReadPath operations before eviction
evict-path-count: 5 # How many paths to evict at a time
batch-size: 1 # Size of each batch of requests  
epoch-time: 10 # How many milliseconds between each epoch
trace: false # Whether to use opentelemetry and jaeger
Z: 1 # number of real blocks per bucket
S: 9 # number of dummy blocks per bucket
shift: 1 # 2^shift is the tree branching factor
tree-height: 8 # height of the tree