endpoints:
  - exposed_ip: localhost
    local_bind_ip: localhost
    port: 8748
    id: 0
    replicaid: 0
    raftport: 3124
  - exposed_ip: localhost
    local_bind_ip: localhost
    port: 8749
    id: 0
    replicaid: 1
    raftport: 3125
  - exposed_ip: localhost
    local_bind_ip: localhost
    port: 8750
    id: 0
    replicaid: 2
    raftport: 3126