endpoints:
  - exposed_ip: 192.168.252.115
    local_bind_ip: 192.168.252.115
    deploy_host: host1
    port: 8751
    id: 0
    replicaid: 0
    raftport: 3127
  - exposed_ip: 192.168.252.117
    local_bind_ip: 192.168.252.117
    deploy_host: host2
    port: 8752
    id: 0
    replicaid: 1
    raftport: 3128
  - exposed_ip: 192.168.252.119
    local_bind_ip: 192.168.252.119
    deploy_host: host3
    port: 8753
    id: 0
    replicaid: 2
    raftport: 3129