max-blocks-to-send: 5 # The maximum number of blocks to send from each shard node to the oram node during evictions
eviction-rate: 4 # How many ReadPath operations before eviction
batch-size: 1 # Size of each batch of requests