max-blocks-to-send: 5 # The maximum number of blocks to send from each shard node to the oram node during evictions
eviction-rate: 40 # How many ReadPath operations before eviction
batch-size: 2 # Size of each batch of requests  
epoch-time: 10 # How many milliseconds between each epoch
trace: false # Whether to use opentelemetry and jaeger