max-blocks-to-send: 200 # The maximum number of blocks to send from each shard node to the oram node during evictions
eviction-rate: 1 # How many ReadPath operations before eviction
evict-path-count: 200 # How many paths to evict at a time
batch-timeout: 5 # How many milliseconds to wait before sending a batch of blocks to the oram node 
epoch-time: 5 # How many milliseconds between each epoch
trace: false # Whether to use opentelemetry and jaeger
Z: 1 # number of real blocks per bucket
S: 9 # number of dummy blocks per bucket
shift: 1 # 2^shift is the tree branching factor
tree-height: 20 # height of the tree
redis-pipeline-size: 150 # number of requests to pipeline to redis
max-requests: 40000 # maximum number of requests in flight at the client
log: false # Whether to log
profile: false # Whether to profile