endpoints:
  - ip: 127.0.0.1
    port: 8748
    id: 0
    replicaid: 0
    raftport: 3124
    local_bind_ip: 127.0.0.1
  - ip: 127.0.0.1
    port: 8749
    id: 0
    replicaid: 1
    raftport: 3125
    local_bind_ip: 127.0.0.1
  - ip: 127.0.0.1
    port: 8750
    id: 0
    replicaid: 2
    raftport: 3126
    local_bind_ip: 127.0.0.1