# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install redis
    - run:  sudo apt-get install -y redis-tools redis-server
    - name: Verify that redis is up
    - run: redis-cli ping
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
